name: CI
on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            shell: bash
            neovim_install: |
              mkdir -p /tmp/nvim
              wget -q https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage -O /tmp/nvim/nvim.appimage
              cd /tmp/nvim
              chmod a+x ./nvim.appimage
              ./nvim.appimage --appimage-extract
              echo "/tmp/nvim/squashfs-root/usr/bin/" >> $GITHUB_PATH
            run_tests: |
              nvim --version
              [ ! -d tests ] && exit 0
              nvim --headless -u tests/init.lua -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/init.lua', sequential = true}"
          - os: windows-latest
            shell: pwsh
            neovim_install: |
              C:\msys64\usr\bin\wget.exe -q https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip
              7z x nvim-win64.zip
              Add-Content $env:GITHUB_PATH ".\nvim-win64\bin\"
            run_tests: |
              nvim --version
              if (-not (Test-Path tests)) { exit 0 }
              nvim --headless -u tests/init.lua -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/init.lua', sequential = true}"
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        run: ${{ matrix.neovim_install }}
      - name: Run Tests
        run: ${{ matrix.run_tests }}
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: tests
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: borrowed.nvim
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(build): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
