name: Run tests

on:
  pull_request:
  push:
  schedule:
    - cron: "0 12 * * *"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p stylua --run "stylua -f .stylua.toml --check ."

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        neovim: [stable, nightly]

        include:
          - os: ubuntu-latest
            run_tests: |
              nvim --version
              [ ! -d tests ] && exit 0
              nvim --headless -u tests/init.lua -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/init.lua', sequential = true}"
          - os: macos-latest
            run_tests: |
              nvim --version
              [ ! -d tests ] && exit 0
              nvim --headless -u tests/init.lua -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/init.lua', sequential = true}"
          - os: windows-latest
            shell: pwsh
            run_tests: |
              nvim --version
              if (-not (Test-Path tests)) { exit 0 }
              nvim --headless -u tests/init.lua -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/init.lua', sequential = true}"

    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim ${{ matrix.neovim }}
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim }}
      - name: Run Tests
        run: ${{ matrix.run_tests }}
